import React, { createContext, useContext, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Navigate, NavLink, Route, Routes, useNavigate } from 'react-router-dom';
import { api, date, money, nested, Operation, User } from './api';
import './styles.css';

type AuthValue={user:User|null; loading:boolean; refresh:()=>Promise<void>};
const Auth=createContext<AuthValue>({user:null,loading:true,refresh:async()=>{}});
const useAuth=()=>useContext(Auth);
function AuthProvider({children}:{children:React.ReactNode}) {
  const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true);
  const refresh=async()=>{try{setUser(await api<User>('/api/auth/me'));}catch{setUser(null);}finally{setLoading(false);}};
  useEffect(()=>{refresh()},[]);
  return <Auth.Provider value={{user,loading,refresh}}>{children}</Auth.Provider>;
}
function Guard({children,admin=false}:{children:React.ReactNode;admin?:boolean}) {
  const {user,loading}=useAuth(); if(loading)return <div className="loader">Carregando…</div>;
  if(!user)return <Navigate to="/login" replace/>; if(admin&&!user.ehAdministrador)return <Navigate to="/" replace/>; return children;
}
function CampoSenha(props:React.InputHTMLAttributes<HTMLInputElement>){
  const [mostrar,setMostrar]=useState(false);
  return <span className="pwd"><input {...props} type={mostrar?'text':'password'}/><button type="button" tabIndex={-1} onClick={()=>setMostrar(v=>!v)}>{mostrar?'Ocultar':'Mostrar'}</button></span>;
}
function Login(){
  const {user,refresh}=useAuth(),nav=useNavigate(); const [error,setError]=useState(''),[busy,setBusy]=useState(false);
  if(user)return <Navigate to="/" replace/>;
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);
    try{await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:f.get('email'),password:f.get('password'),rememberMe:f.get('rememberMe')==='on'})});await refresh();nav('/');}
    catch(x){setError((x as Error).message)}finally{setBusy(false)}}
  return <div className="login"><section className="login-brand"><img src="/img/onrtdpj-logo-tagline.png"/><div><span>Sistema interno</span><h1>Gestão financeira clara, segura e centralizada.</h1><p>Contas, documentos, fornecedores e aprovações em um único fluxo.</p></div></section>
    <main className="login-card"><img src="/img/onrtdpj-icone.png"/><p className="eyebrow">Bem-vindo</p><h2>Acesse sua conta</h2><p>Use suas credenciais do sistema para continuar.</p>
      <form onSubmit={submit}><label>E-mail<input name="email" type="email" required autoFocus/></label><label>Senha<CampoSenha name="password" required/></label><label className="check"><input name="rememberMe" type="checkbox"/> Manter conectado</label>{error&&<div className="alert error">{error}</div>}<button disabled={busy}>{busy?'Entrando…':'Entrar no sistema'}</button></form></main></div>;
}
const groups=[['Painel',[['Início','/']]],['Financeiro',[['Contas a pagar','/contas-a-pagar'],['Boletos','/boletos'],['Notas fiscais','/notas-fiscais'],['Relatórios','/relatorios']]],['Cadastros',[['Fornecedores','/fornecedores'],['Contas bancárias','/contas-bancarias'],['Cartões','/cartoes'],['Categorias','/categorias'],['Centros de custo','/centros-de-custo']]],['Documentos',[['Central de documentos','/central-de-documentos']]]] as const;
function Layout(){
 const {user}=useAuth(),[open,setOpen]=useState(false);
 return <Guard><div className="shell"><aside className={open?'open':''}><div className="brand"><img src="/img/onrtdpj-icone.png"/><b>Financeiro <strong>ONRTDPJ</strong></b></div><nav>{groups.map(([g,items])=><section key={g}><small>{g}</small>{items.map(([l,h])=><NavLink key={h} to={h} end={h==='/' } onClick={()=>setOpen(false)}>{l}</NavLink>)}</section>)}{user?.ehAdministrador&&<section><small>Administração</small><NavLink to="/auditoria">Auditoria</NavLink><NavLink to="/usuarios">Usuários</NavLink><NavLink to="/configuracoes-ia">Configurações de IA</NavLink></section>}</nav><div className="profile"><span>{user?.nome}<small>{user?.papeis.join(' · ')}</small></span><button className="link" onClick={async()=>{await api('/api/auth/logout',{method:'POST'});location.assign('/login')}}>Sair</button></div></aside><main className="main"><header><button className="menu" onClick={()=>setOpen(!open)}>☰</button><span>Ambiente financeiro</span></header><div className="content"><OutletRoutes/></div></main><Chat/></div></Guard>;
}
function OutletRoutes(){return <Routes><Route index element={<Dashboard/>}/><Route path="contas-a-pagar" element={<Contas/>}/><Route path="contas-a-pagar/novo" element={<Navigate to="/contas-a-pagar"/>}/><Route path="contas-a-pagar/:id" element={<Navigate to="/contas-a-pagar"/>}/><Route path="fornecedores" element={<Crud config={configs.fornecedores}/>}/><Route path="fornecedores/novo" element={<Navigate to="/fornecedores"/>}/><Route path="categorias" element={<Crud config={configs.categorias}/>}/><Route path="centros-de-custo" element={<Crud config={configs.centros}/>}/><Route path="contas-bancarias" element={<Crud config={configs.bancos}/>}/><Route path="cartoes" element={<Crud config={configs.cartoes}/>}/><Route path="notas-fiscais" element={<Crud config={configs.notas}/>}/><Route path="boletos" element={<Crud config={configs.boletos}/>}/><Route path="central-de-documentos" element={<Documentos/>}/><Route path="relatorios" element={<Relatorios/>}/><Route path="auditoria" element={<Admin><Auditoria/></Admin>}/><Route path="usuarios" element={<Admin><Usuarios/></Admin>}/><Route path="configuracoes-ia" element={<Admin><Configuracoes/></Admin>}/><Route path="*" element={<NotFound/>}/></Routes>}
function Admin({children}:{children:React.ReactNode}){return <Guard admin>{children}</Guard>}
function Title({title,subtitle,action}:{title:string;subtitle?:string;action?:React.ReactNode}){return <div className="title"><div><p className="eyebrow">Financeiro ONRTDPJ</p><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}
function Loading(){return <div className="card empty">Carregando dados…</div>}
function useLoad<T>(url:string){const [data,setData]=useState<T>(),[error,setError]=useState('');const load=()=>{if(!url)return;api<T>(url).then(setData).catch(e=>setError(e.message))};useEffect(()=>{load()},[url]);return{data,error,load}}
function Dashboard(){const {data}=useLoad<any>('/api/dashboard');if(!data)return <Loading/>;const cards=[['Em aberto',data.totalEmAberto,data.quantidadeEmAberto],['Vencidas',data.totalVencidas,data.quantidadeVencidas],['A pagar hoje',data.totalAPagarHoje],['Próximos 7 dias',data.totalAPagarProximos7Dias],['Pago no mês',data.totalPagoNoMes],['Pago no ano',data.totalPagoNoAno]];return <><Title title="Painel financeiro" subtitle="Visão consolidada das obrigações e pagamentos."/><div className="metrics">{cards.map(c=><article key={c[0]}><span>{c[0]}</span><b>{money(c[1])}</b>{c[2]!=null&&<small>{c[2]} lançamento(s)</small>}</article>)}</div><section className="card"><h2>Próximos vencimentos</h2><Table rows={data.proximosVencimentos||[]} cols={[['Fornecedor','fornecedor'],['Descrição','descricao'],['Vencimento','vencimento','date'],['Valor','valorFinal','money']]}/></section></>}
type Field={name:string;label:string;type?:string;required?:boolean;options?:[string,string][];source?:string;optionLabel?:string};
type Config={title:string;subtitle:string;endpoint:string;cols:[string,string,string?][];fields:Field[];delete?:boolean};
const configs:Record<string,Config>={
 fornecedores:{title:'Fornecedores',subtitle:'Cadastro e dados de relacionamento.',endpoint:'/api/fornecedores?incluirExcluidos=false',cols:[['Razão social','razaoSocial'],['Nome fantasia','nomeFantasia'],['CNPJ / CPF','cnpjCpf'],['Contato','email']],fields:[{name:'razaoSocial',label:'Razão social',required:true},{name:'nomeFantasia',label:'Nome fantasia'},{name:'cnpjCpf',label:'CNPJ / CPF',required:true},{name:'inscricaoEstadual',label:'Inscrição estadual'},{name:'endereco',label:'Endereço'},{name:'telefone',label:'Telefone'},{name:'email',label:'E-mail',type:'email'},{name:'contatoResponsavel',label:'Contato responsável'},{name:'formaPagamentoPadraoId',label:'Forma padrão',source:'/api/formas-pagamento?apenasAtivos=true',optionLabel:'nome'},{name:'observacoes',label:'Observações'}],delete:true},
 categorias:{title:'Categorias',subtitle:'Classificação dos lançamentos.',endpoint:'/api/categorias?apenasAtivos=false',cols:[['Nome','nome'],['Descrição','descricao'],['Situação','ativo','bool']],fields:[{name:'nome',label:'Nome',required:true},{name:'descricao',label:'Descrição'}]},
 centros:{title:'Centros de custo',subtitle:'Estrutura de alocação financeira.',endpoint:'/api/centros-custo?apenasAtivos=false',cols:[['Nome','nome'],['Descrição','descricao'],['Situação','ativo','bool']],fields:[{name:'nome',label:'Nome',required:true},{name:'descricao',label:'Descrição'}]},
 bancos:{title:'Contas bancárias',subtitle:'Contas da empresa disponíveis para pagamentos.',endpoint:'/api/contas-bancarias?apenasAtivas=false',cols:[['Apelido','apelido'],['Banco','banco'],['Agência','agencia'],['Conta','conta'],['Situação','ativo','bool']],fields:[{name:'apelido',label:'Apelido',required:true},{name:'banco',label:'Banco',required:true},{name:'agencia',label:'Agência',required:true},{name:'conta',label:'Conta',required:true},{name:'tipo',label:'Tipo',options:[['Corrente','Corrente'],['Poupanca','Poupança']]}]},
 cartoes:{title:'Cartões',subtitle:'Cartões corporativos e limites.',endpoint:'/api/cartoes',cols:[['Apelido','apelido'],['Instituição','instituicaoFinanceira'],['Final','ultimosQuatroDigitos'],['Limite','limite','money'],['Status','status']],fields:[{name:'apelido',label:'Apelido',required:true},{name:'instituicaoFinanceira',label:'Instituição',required:true},{name:'bandeira',label:'Bandeira',required:true},{name:'ultimosQuatroDigitos',label:'Últimos 4 dígitos',required:true},{name:'limite',label:'Limite',type:'number'},{name:'diaFechamento',label:'Dia de fechamento',type:'number'},{name:'diaVencimento',label:'Dia de vencimento',type:'number'},{name:'responsavelId',label:'Responsável (ID)',type:'hidden'}]},
 notas:{title:'Notas fiscais',subtitle:'Notas vinculadas aos fornecedores.',endpoint:'/api/notas-fiscais',cols:[['Número','numero'],['Fornecedor','fornecedor.razaoSocial'],['Emissão','emissao','date'],['Valor','valor','money']],fields:[{name:'fornecedorId',label:'Fornecedor',source:'/api/fornecedores?incluirExcluidos=false',optionLabel:'razaoSocial',required:true},{name:'numero',label:'Número',required:true},{name:'serie',label:'Série'},{name:'emissao',label:'Emissão',type:'date',required:true},{name:'valor',label:'Valor',type:'number',required:true},{name:'vencimento',label:'Vencimento',type:'date'},{name:'observacoes',label:'Observações'}],delete:true},
 boletos:{title:'Boletos',subtitle:'Controle de títulos e linhas digitáveis.',endpoint:'/api/boletos',cols:[['Número','numero'],['Fornecedor','fornecedor.razaoSocial'],['Vencimento','vencimento','date'],['Valor','valor','money'],['Status','status']],fields:[{name:'fornecedorId',label:'Fornecedor',source:'/api/fornecedores?incluirExcluidos=false',optionLabel:'razaoSocial',required:true},{name:'contaPagarId',label:'Conta a pagar',source:'/api/contas-a-pagar',optionLabel:'descricao',required:true},{name:'numero',label:'Número',required:true},{name:'linhaDigitavel',label:'Linha digitável',required:true},{name:'codigoBarras',label:'Código de barras'},{name:'valor',label:'Valor',type:'number',required:true},{name:'vencimento',label:'Vencimento',type:'date',required:true},{name:'banco',label:'Banco'},{name:'status',label:'Status',options:[['EmAberto','Em aberto'],['Pago','Pago'],['Vencido','Vencido'],['Cancelado','Cancelado']]},{name:'observacoes',label:'Observações'}],delete:true}
};
function Table({rows,cols,onClick}:{rows:any[];cols:[string,string,string?][];onClick?:(x:any)=>void}){return <div className="table-wrap"><table><thead><tr>{cols.map(c=><th key={c[1]}>{c[0]}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={r.id||i} onClick={()=>onClick?.(r)} className={onClick?'clickable':''}>{cols.map(c=>{const v=nested(r,c[1]);return <td key={c[1]}>{c[2]==='money'?money(v):c[2]==='date'?date(v):c[2]==='bool'?(v?'Ativo':'Inativo'):(v??'—')}</td>})}</tr>):<tr><td colSpan={cols.length} className="empty">Nenhum registro encontrado.</td></tr>}</tbody></table></div>}
function FieldInput({field,value,onChange}:{field:Field;value:any;onChange:(v:any)=>void}){const {data}=useLoad<any[]>(field.source||'');if(field.options||field.source){const opts=field.options||(data||[]).map(x=>[x.id,String(nested(x,field.optionLabel||'nome'))] as [string,string]);return <label>{field.label}<select required={field.required} value={value||''} onChange={e=>onChange(e.target.value)}><option value="">Selecione</option>{opts.map(o=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select></label>}return <label>{field.label}<input type={field.type||'text'} step={field.type==='number'?'0.01':undefined} required={field.required} value={value??''} onChange={e=>onChange(field.type==='number'?Number(e.target.value):e.target.value)}/></label>}
function Crud({config}:{config:Config}){const {user}=useAuth(),{data,load}=useLoad<any[]>(config.endpoint),[editing,setEditing]=useState<any|null>(null),[msg,setMsg]=useState('');
 async function save(e:React.FormEvent){e.preventDefault();const body={...editing};delete body.id;delete body.criadoEm;delete body.atualizadoEm;Object.keys(body).filter(k=>typeof body[k]==='object').forEach(k=>delete body[k]);try{const path=config.endpoint.split('?')[0]+(editing.id?'/'+editing.id:'');const result:any=await api(path,{method:editing.id?'PUT':'POST',body:JSON.stringify(body)});const op:Operation=result.operacao||result;if(op.sucesso===false)throw new Error(op.erros.join(' '));setEditing(null);setMsg('Registro salvo com sucesso.');load()}catch(x){setMsg((x as Error).message)}}
 return <><Title title={config.title} subtitle={config.subtitle} action={<button onClick={()=>setEditing(config===configs.cartoes?{responsavelId:user?.id}:{})}>Novo cadastro</button>}/>{msg&&<div className="alert">{msg}</div>}<section className="card"><Table rows={data||[]} cols={config.cols} onClick={setEditing}/></section>{editing&&<div className="modal"><form className="dialog" onSubmit={save}><h2>{editing.id?'Editar':'Novo'} registro</h2><div className="form-grid">{config.fields.map(f=><FieldInput key={f.name} field={f} value={editing[f.name]} onChange={v=>setEditing({...editing,[f.name]:v})}/>)}</div><div className="actions"><button type="button" className="secondary" onClick={()=>setEditing(null)}>Cancelar</button><button>Salvar</button></div></form></div>}</>}
const camposConta:[string,string,string?][]=[['descricao','Descrição','text'],['vencimento','Vencimento','date'],['valorOriginal','Valor original','number'],['desconto','Desconto','number'],['juros','Juros','number'],['multa','Multa','number']];
function Contas(){
 const {data,load}=useLoad<any[]>('/api/contas-a-pagar'),{data:fornecedores}=useLoad<any[]>('/api/fornecedores?incluirExcluidos=false');
 const [editing,setEditing]=useState<any|null>(null),[msg,setMsg]=useState('');
 async function salvar(e:React.FormEvent){e.preventDefault();const body={...editing};delete body.id;delete body.criadoEm;delete body.atualizadoEm;Object.keys(body).filter(k=>typeof body[k]==='object').forEach(k=>delete body[k]);try{const r:any=await api('/api/contas-a-pagar'+(editing.id?'/'+editing.id:''),{method:editing.id?'PUT':'POST',body:JSON.stringify(body)});const op=r.operacao||r;if(op.sucesso===false)throw new Error(op.erros.join(' '));setEditing(null);setMsg('Conta salva com sucesso.');load()}catch(x){setMsg((x as Error).message)}}
 async function action(name:string){const motivo=name==='rejeitar'?prompt('Motivo da rejeição:'):undefined;const r:any=await api('/api/contas-a-pagar/'+editing.id+'/'+name,{method:'POST',body:motivo?JSON.stringify({motivo}):undefined});if(r.sucesso===false){setMsg(r.erros.join(' '));return}setEditing(null);setMsg('Ação registrada com sucesso.');load()}
 return <><Title title="Contas a pagar" subtitle="Lançamentos, aprovação e situação financeira." action={<button onClick={()=>setEditing({desconto:0,juros:0,multa:0})}>Nova conta</button>}/>{msg&&<div className="alert">{msg}</div>}<section className="card"><Table rows={data||[]} onClick={x=>setEditing({...x})} cols={[['Descrição','descricao'],['Fornecedor','fornecedor.razaoSocial'],['Vencimento','vencimento','date'],['Valor final','valorFinal','money'],['Aprovação','statusAprovacao'],['Financeiro','statusFinanceiro']]}/></section>
  {editing&&<div className="modal"><form className="dialog" onSubmit={salvar}><h2>{editing.id?'Detalhe da conta':'Nova conta'}</h2>{editing.id&&<p><b>Aprovação:</b> {editing.statusAprovacao} · <b>Financeiro:</b> {editing.statusFinanceiro}</p>}<div className="form-grid">
    <label>Fornecedor<select required value={editing.fornecedorId||''} onChange={e=>setEditing({...editing,fornecedorId:e.target.value})}><option value="">Selecione</option>{fornecedores?.map(x=><option key={x.id} value={x.id}>{x.razaoSocial}</option>)}</select></label>
    {camposConta.map(([n,l,t])=><label key={n}>{l}<input required={['descricao','vencimento','valorOriginal'].includes(n)} type={t} step={t==='number'?'0.01':undefined} value={editing[n]??''} onChange={e=>setEditing({...editing,[n]:t==='number'?Number(e.target.value):e.target.value})}/></label>)}
   </div><div className="actions">{editing.id&&<><button type="button" className="success" onClick={()=>action('aprovar')}>Aprovar</button><button type="button" className="danger" onClick={()=>action('rejeitar')}>Rejeitar</button></>}<button type="button" className="secondary" onClick={()=>setEditing(null)}>Cancelar</button><button>Salvar</button></div></form></div>}
 </>}
function Documentos(){const {data,load}=useLoad<any>('/api/documentos?pagina=1&tamanhoPagina=20'),[msg,setMsg]=useState('');async function upload(e:React.ChangeEvent<HTMLInputElement>){if(!e.target.files)return;const f=new FormData();[...e.target.files].forEach(x=>f.append('arquivos',x));try{await api('/api/documentos',{method:'POST',body:f});setMsg('Arquivos enviados para processamento.');load()}catch(x){setMsg((x as Error).message)}}return <><Title title="Central de documentos" subtitle="Envie arquivos para leitura e classificação por IA." action={<label className="button">Enviar arquivos<input hidden multiple type="file" onChange={upload}/></label>}/>{msg&&<div className="alert">{msg}</div>}<section className="card"><Table rows={data?.itens||[]} cols={[['Arquivo','nomeArquivo'],['Tipo','tipoDetectado'],['Status','status'],['Confiança','confiancaGeral'],['Enviado em','criadoEm','date']]}/></section></>}
function Relatorios(){return <><Title title="Relatórios" subtitle="Exporte as contas a pagar no formato necessário."/><div className="cards"><a className="card download" href="/relatorios/contas-a-pagar.xlsx">Planilha Excel <span>.xlsx</span></a><a className="card download" href="/relatorios/contas-a-pagar.csv">Arquivo de dados <span>.csv</span></a><a className="card download" href="/relatorios/contas-a-pagar.pdf">Documento PDF <span>.pdf</span></a></div></>}
function Auditoria(){const {data}=useLoad<any[]>('/api/auditoria?limite=200');return <><Title title="Auditoria" subtitle="Registro das alterações realizadas no sistema."/><section className="card"><Table rows={data||[]} cols={[['Data','data','date'],['Usuário','usuarioNome'],['Ação','acao'],['Entidade','tipoEntidade'],['Identificador','entidadeId']]}/></section></>}
function Usuarios(){const {data}=useLoad<any[]>('/api/usuarios');return <><Title title="Usuários" subtitle="Acessos e perfis do sistema."/><section className="card"><Table rows={(data||[]).map(x=>({...x.usuario,papeis:x.papeis.join(', ')}))} cols={[['Nome','nome'],['E-mail','email'],['Perfis','papeis'],['Situação','ativo','bool'],['Último login','ultimoLogin','date']]}/></section></>}
function Configuracoes(){return <><Title title="Configurações de IA" subtitle="Provedor, modelo e chave usados na leitura de documentos e no chat."/><div className="cards">{['Documentos','Chat'].map(x=><IaCard key={x} name={x}/>)}</div></>}
type ResumoIa={configuradoPeloPainel:boolean;ativo:boolean;provedor:string|null;modelo:string|null;timeoutSegundos:number;apiKeyDefinida:boolean};
function IaCard({name}:{name:string}){
 const {data,load}=useLoad<ResumoIa>('/api/configuracoes-ia/'+name),[msg,setMsg]=useState(''),[editing,setEditing]=useState<any|null>(null);
 async function testar(){const r:any=await api('/api/configuracoes-ia/'+name+'/testar',{method:'POST'});setMsg(r.sucesso?'Conexão funcionando.':r.erros.join(' '))}
 async function restaurar(){if(!confirm('Remover a configuração salva aqui e voltar a usar as variáveis de ambiente?'))return;await api('/api/configuracoes-ia/'+name,{method:'DELETE'});setMsg('Configuração removida — usando variáveis de ambiente.');load()}
 async function salvar(e:React.FormEvent){e.preventDefault();try{const r:any=await api('/api/configuracoes-ia/'+name,{method:'PUT',body:JSON.stringify(editing)});if(r.sucesso===false)throw new Error(r.erros.join(' '));setEditing(null);setMsg('Configuração salva com sucesso.');load()}catch(x){setMsg((x as Error).message)}}
 return <article className="card"><h2>{name}</h2><p><b>Provedor:</b> {data?.provedor||'Não configurado'}</p><p><b>Modelo:</b> {data?.modelo||'—'}</p><p><b>Status:</b> {data?.ativo?'Ativo':'Inativo'}</p><p><b>Chave de API:</b> {data?.apiKeyDefinida?'Definida':'Não definida'}</p><p><b>Origem:</b> {data?.configuradoPeloPainel?'Editada nesta tela':'Variáveis de ambiente'}</p>
  <div className="actions full"><button type="button" className="secondary" onClick={testar}>Testar conexão</button>{data?.configuradoPeloPainel&&<button type="button" className="danger" onClick={restaurar}>Restaurar padrão</button>}<button type="button" onClick={()=>setEditing({ativo:data?.ativo??true,provedor:data?.provedor||'Gemini',modelo:data?.modelo||'',apiKey:'',timeoutSegundos:data?.timeoutSegundos||90})}>Editar</button></div>
  {msg&&<p>{msg}</p>}
  {editing&&<div className="modal"><form className="dialog" onSubmit={salvar}><h2>Configurar {name}</h2><div className="form-grid">
    <label>Provedor<select value={editing.provedor} onChange={e=>setEditing({...editing,provedor:e.target.value})}><option value="Gemini">Gemini</option><option value="OpenAi">OpenAI</option><option value="Anthropic">Anthropic</option></select></label>
    <label>Modelo<input required value={editing.modelo} onChange={e=>setEditing({...editing,modelo:e.target.value})}/></label>
    <label>Chave de API<CampoSenha autoComplete="off" placeholder={data?.apiKeyDefinida?'Deixe em branco para manter a atual':'Obrigatória na primeira configuração'} value={editing.apiKey} onChange={e=>setEditing({...editing,apiKey:e.target.value})}/></label>
    <label>Timeout (segundos)<input type="number" required min={1} value={editing.timeoutSegundos} onChange={e=>setEditing({...editing,timeoutSegundos:Number(e.target.value)})}/></label>
    <label className="check"><input type="checkbox" checked={editing.ativo} onChange={e=>setEditing({...editing,ativo:e.target.checked})}/> Ativo</label>
   </div><div className="actions"><button type="button" className="secondary" onClick={()=>setEditing(null)}>Cancelar</button><button>Salvar</button></div></form></div>}
 </article>
}
function Chat(){const [open,setOpen]=useState(false),[messages,setMessages]=useState<{papel:string;texto:string}[]>([]),[text,setText]=useState('');async function send(e:React.FormEvent){e.preventDefault();if(!text.trim())return;const q=text;setText('');setMessages(m=>[...m,{papel:'user',texto:q}]);try{const r:any=await api('/api/chat',{method:'POST',body:JSON.stringify({historico:messages,mensagem:q})});setMessages(m=>[...m,{papel:'model',texto:r.texto}])}catch(x){setMessages(m=>[...m,{papel:'model',texto:(x as Error).message}])}}return <div className={'chat '+(open?'open':'')}><button className="chat-toggle" onClick={()=>setOpen(!open)}>✦</button>{open&&<section><header><b>Assistente financeiro</b><button className="link" onClick={()=>setOpen(false)}>×</button></header><div className="messages">{messages.length?messages.map((m,i)=><p key={i} className={m.papel}>{m.texto}</p>):<div className="empty">Pergunte sobre contas, vencimentos ou documentos.</div>}</div><form onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Digite sua pergunta…"/><button>Enviar</button></form></section>}</div>}
function NotFound(){return <div className="card empty"><h1>Página não encontrada</h1><NavLink to="/">Voltar ao início</NavLink></div>}
function App(){return <AuthProvider><BrowserRouter><Routes><Route path="/login" element={<Login/>}/><Route path="/*" element={<Layout/>}/></Routes></BrowserRouter></AuthProvider>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
